libpath <- "C:/Users/User/Documents/R/win-library/4.6"; .libPaths(c(libpath, .libPaths()))
suppressMessages({library(haven); library(dplyr)})
fw <- "K:/DATEIEN/Data/PIP2022/_PIP_COLLECTION_v2022-03/03 pip_analysis/ASPM_Extended_Replication_2022/Framework"
d <- as.data.frame(read_dta(file.path(fw,"datasets/pip_ts_aspm.dta")))
euvars <- c("p601","p604","p611","p612","p614","p615","p625","p631","p643","p645")
cat("EU-Vars vorhanden:", paste(euvars[euvars %in% names(d)], collapse=" "), "\n")
cat("FEHLEN:", paste(setdiff(euvars, names(d)), collapse=" "), "\n")
ext <- as.data.frame(read_dta(file.path(fw,"datasets/external_data.dta")))
cat("external_data cols:", paste(grep("population|gdp", names(ext), value=TRUE, ignore.case=TRUE), collapse=" "), "\n")
cat("max techq (g105):", max(d$g105,na.rm=TRUE), " Jahre bis", max(d$g103,na.rm=TRUE), "\n")
